# Generated by Django 4.2.1 on 2023-06-09 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vip', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('invite_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('referral_code', models.CharField(max_length=6, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('vip_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vip.vip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=25)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(choices=[('first_bank', 'First Bank'), ('fCM', 'First City Monument Bank'), ('Access Bank Plc', 'Access Bank Plc'), ('Fidelity Bank Plc', 'Fidelity Bank Plc'), ('First Bank of Nigeria Limited', 'First Bank of Nigeria Limited'), ('Guaranty Trust Holding Company Plc', 'Guaranty Trust Holding Company Plc'), ('Union Bank of Nigeria Plc', 'Union Bank of Nigeria Plc'), ('United Bank for Africa Plc', 'United Bank for Africa Plc'), ('Zenith Bank Plc', 'Zenith Bank Plc'), ('Citibank Nigeria Limited', 'Citibank Nigeria Limited'), ('Ecobank Nigeria', 'Ecobank Nigeria'), ('Heritage Bank Plc', 'Heritage Bank Plc'), ('Keystone Bank Limited', 'Keystone Bank Limited'), ('Optimus Bank Limited', 'Optimus Bank Limited'), ('Polaris Bank Limited. The successor to Skye Bank Plc', 'Polaris Bank Limited. The successor to Skye Bank Plc'), ('Stanbic IBTC Bank Plc', 'Stanbic IBTC Bank Plc'), ('Standard Chartered', 'Standard Chartered'), ('Sterling Bank Plc', 'Sterling Bank Plc'), ('Titan Trust bank', 'Titan Trust bank'), ('Unity Bank Plc', 'Unity Bank Plc'), ('Wema Bank Plc', 'Wema Bank Plc'), ('FairMoney Microfinance Bank', 'FairMoney Microfinance Bank'), ('Sparkle Bank', 'Sparkle Bank'), ('Kuda Bank', 'Kuda Bank'), ('Moniepoint Microfinance Bank', 'Moniepoint Microfinance Bank'), ('Opay', 'Opay'), ('Palmpay', 'Palmpay'), ('Rubies Bank', 'Rubies Bank'), ('VFD Microfinance Bank', 'VFD Microfinance Bank'), ('Mint Finex MFB', 'Mint Finex MFB'), ('Mkobo MFB', 'Mkobo MFB'), ('Raven bank', 'Raven bank'), ('Guaranty Trust Holding Company Plc', 'Guaranty Trust Holding Company Plc'), ('Fidelity Bank Plc', 'Fidelity Bank Plc')], max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadCashOutProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bankdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('referral', 'Referral')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_of_invites', models.IntegerField(default=0)),
                ('team_recharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comissions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investing_reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('proof', models.ImageField(upload_to='media/deposit_proofs/')),
                ('narration', models.TextField(max_length=120)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requested_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
