# Generated by Django 4.2.1 on 2023-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='proof',
            field=models.ImageField(upload_to='deposit_proofs/'),
        ),
    ]
