# Generated by Django 4.2.1 on 2023-06-08 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawaltransactionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requested_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepositTransactionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('failed', 'failed'), ('successful', 'successful')], default='pending', max_length=50)),
                ('is_aproved', models.BooleanField(default=False)),
                ('proof', models.ImageField(upload_to='media/deposit_proofs/')),
                ('narration', models.TextField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requested_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
