# Generated by Django 4.2.1 on 2023-05-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_invite_code_profile_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
