# Generated by Django 4.2.1 on 2023-06-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='proof',
            field=models.ImageField(upload_to='deposit_proofs/', verbose_name='deposit proof'),
        ),
    ]
