# Generated by Django 4.2.1 on 2023-06-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_withdrawalrequest_alter_bankdetails_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='withdrawal_transaction',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bankdetails'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
