# Generated by Django 4.2.1 on 2023-06-09 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_withdrawalrequest_withdrawal_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
