# Generated by Django 4.2.1 on 2023-06-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_bankdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='bank_details',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
