# Generated by Django 4.2.1 on 2023-06-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_withdrawalrequest_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bankdetails'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankdetails', to=settings.AUTH_USER_MODEL),
        ),
    ]
