# Generated by Django 4.2.1 on 2023-06-09 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_withdrawalrequest_bank_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittransactionrequest',
            old_name='is_aproved',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='deposittransactionrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposittransactionrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposittransactionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
