# Generated by Django 4.2.1 on 2023-06-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='circle',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vip_circle_days', to='vip.viplevel'),
        ),
        migrations.AlterField(
            model_name='viplevel',
            name='level',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
