# Generated by Django 4.2.1 on 2023-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='circle_days',
        ),
        migrations.AddField(
            model_name='viplevel',
            name='circle_days',
            field=models.IntegerField(null=True),
        ),
    ]
