# Generated by Django 4.2.1 on 2023-06-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_vip_circle_alter_viplevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='circle',
        ),
        migrations.AlterField(
            model_name='viplevel',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
