# Generated by Django 4.2.1 on 2023-06-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0004_vip_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='price',
        ),
    ]
